name: Build and deploy Node.js app to Azure Web App - valkwame

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Change directory to the project folder
        run: cd myreactproject

      - name: Install dependencies, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Zip Release
        uses: TheDoctor0/zip-release@0.7.1
        with:
          # Filename for archive
          filename: release.zip
          # Base path for archive files
          path: ./myreactproject/build/*
          # Working directory before zipping
          directory: myreactproject

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: myreactproject/release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip node-app/release.zip -d myreactproject

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'valkwame'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_37A3446E461A479FBD327D0A45A82E31 }}
          package: myreactproject
